const itemsSelect = [
    { "value": "pizza", "label": "Pizza" },
    { "value": "burger", "label": "Burger" },
    { "value": "hot_dog", "label": "Hot Dog" },
    { "value": "bbq", "label": "Barbecue" },
    { "value": "steakhouse", "label": "Steakhouse" },
    { "value": "seafood", "label": "Seafood" },
    { "value": "sushi", "label": "Sushi" },
    { "value": "ramen", "label": "Ramen" },
    { "value": "udon", "label": "Udon" },
    { "value": "tempura", "label": "Tempura" },
    { "value": "yakitori", "label": "Yakitori" },
    { "value": "korean", "label": "Korean" },
    { "value": "chinese", "label": "Chinese" },
    { "value": "thai", "label": "Thai" },
    { "value": "vietnamese", "label": "Vietnamese" },
    { "value": "indian", "label": "Indian" },
    { "value": "pakistani", "label": "Pakistani" },
    { "value": "mexican", "label": "Mexican" },
    { "value": "tacos", "label": "Tacos" },
    { "value": "burritos", "label": "Burritos" },
    { "value": "italian", "label": "Italian" },
    { "value": "pasta", "label": "Pasta" },
    { "value": "risotto", "label": "Risotto" },
    { "value": "french", "label": "French" },
    { "value": "greek", "label": "Greek" },
    { "value": "turkish", "label": "Turkish" },
    { "value": "middle_eastern", "label": "Middle Eastern" },
    { "value": "lebanese", "label": "Lebanese" },
    { "value": "brazilian", "label": "Brazilian" },
    { "value": "portuguese", "label": "Portuguese" },
    { "value": "spanish", "label": "Spanish" },
    { "value": "argentinian", "label": "Argentinian" },
    { "value": "peruvian", "label": "Peruvian" },
    { "value": "caribbean", "label": "Caribbean" },
    { "value": "african", "label": "African" },
    { "value": "ethiopian", "label": "Ethiopian" },
    { "value": "moroccan", "label": "Moroccan" },
    { "value": "vegan", "label": "Vegan" },
    { "value": "vegetarian", "label": "Vegetarian" },
    { "value": "gluten_free", "label": "Gluten Free" },
    { "value": "healthy", "label": "Healthy" },
    { "value": "organic", "label": "Organic" },
    { "value": "salads", "label": "Salads" },
    { "value": "sandwiches", "label": "Sandwiches" },
    { "value": "wraps", "label": "Wraps" },
    { "value": "breakfast", "label": "Breakfast" },
    { "value": "brunch", "label": "Brunch" },
    { "value": "bakery", "label": "Bakery" },
    { "value": "desserts", "label": "Desserts" },
    { "value": "ice_cream", "label": "Ice Cream" },
    { "value": "donuts", "label": "Donuts" },
    { "value": "cakes", "label": "Cakes" },
    { "value": "pastries", "label": "Pastries" },
    { "value": "coffee", "label": "Coffee" },
    { "value": "tea", "label": "Tea" },
    { "value": "juice_bar", "label": "Juice Bar" },
    { "value": "smoothies", "label": "Smoothies" },
    { "value": "bubble_tea", "label": "Bubble Tea" },
    { "value": "cocktails", "label": "Cocktails" },
    { "value": "wine_bar", "label": "Wine Bar" },
    { "value": "craft_beer", "label": "Craft Beer" },
    { "value": "fast_food", "label": "Fast Food" },
    { "value": "food_truck", "label": "Food Truck" },
    { "value": "street_food", "label": "Street Food" },
    { "value": "family_restaurant", "label": "Family Restaurant" },
    { "value": "fine_dining", "label": "Fine Dining" },
    { "value": "buffet", "label": "Buffet" },
    { "value": "all_you_can_eat", "label": "All You Can Eat" },
    { "value": "grill", "label": "Grill" },
    { "value": "rotisserie", "label": "Rotisserie" },
    { "value": "fried_chicken", "label": "Fried Chicken" },
    { "value": "wings", "label": "Chicken Wings" },
    { "value": "fish_and_chips", "label": "Fish and Chips" },
    { "value": "dumplings", "label": "Dumplings" },
    { "value": "noodles", "label": "Noodles" },
    { "value": "poke", "label": "Poke" },
    { "value": "ceviche", "label": "Ceviche" },
    { "value": "fondue", "label": "Fondue" },
    { "value": "fondue_chocolate", "label": "Chocolate Fondue" },
    { "value": "crepes", "label": "Crepes" },
    { "value": "waffles", "label": "Waffles" },
    { "value": "pancakes", "label": "Pancakes" },
    { "value": "chocolate", "label": "Chocolate" },
    { "value": "candies", "label": "Candies" },
    { "value": "cookies", "label": "Cookies" },
    { "value": "pies", "label": "Pies" },
    { "value": "soups", "label": "Soups" },
    { "value": "comfort_food", "label": "Comfort Food" },
    { "value": "regional", "label": "Regional Cuisine" },
    { "value": "fusion", "label": "Fusion Cuisine" },
    { "value": "halal", "label": "Halal" },
    { "value": "kosher", "label": "Kosher" },
    { "value": "pet_friendly", "label": "Pet Friendly" },
    { "value": "takeaway", "label": "Takeaway" },
    { "value": "delivery", "label": "Delivery" },
    { "value": "drive_thru", "label": "Drive-Thru" },
    { "value": "late_night", "label": "Late Night" },
    { "value": "romantic", "label": "Romantic" },
    { "value": "rooftop", "label": "Rooftop" },
    { "value": "live_music", "label": "Live Music" },
    { "value": "sports_bar", "label": "Sports Bar" },
    { "value": "gastropub", "label": "Gastropub" }
]
export default itemsSelect